% YOUR MODEL
t(_)::something(grain,agricultur). % TODO
t(_)::something(grain,bank). % TODO
t(_)::something(grain,corn). % TODO
t(_)::something(grain,crop). % TODO
t(_)::something(grain,export). % TODO
t(_)::something(grain,grain). % TODO
t(_)::something(grain,ha). % TODO
t(_)::something(grain,market). % TODO
t(_)::something(grain,mln). % TODO
t(_)::something(grain,pct). % TODO
t(_)::something(grain,price). % TODO
t(_)::something(grain,rate). % TODO
t(_)::something(grain,reuter). % TODO
t(_)::something(grain,said). % TODO
t(_)::something(grain,soviet). % TODO
t(_)::something(grain,thi). % TODO
t(_)::something(grain,tonn). % TODO
t(_)::something(grain,wa). % TODO
t(_)::something(grain,wheat). % TODO
t(_)::something(grain,year). % TODO
t(_)::something(interest,agricultur). % TODO
t(_)::something(interest,bank). % TODO
t(_)::something(interest,corn). % TODO
t(_)::something(interest,crop). % TODO
t(_)::something(interest,export). % TODO
t(_)::something(interest,grain). % TODO
t(_)::something(interest,ha). % TODO
t(_)::something(interest,market). % TODO
t(_)::something(interest,mln). % TODO
t(_)::something(interest,pct). % TODO
t(_)::something(interest,price). % TODO
t(_)::something(interest,rate). % TODO
t(_)::something(interest,reuter). % TODO
t(_)::something(interest,said). % TODO
t(_)::something(interest,soviet). % TODO
t(_)::something(interest,thi). % TODO
t(_)::something(interest,tonn). % TODO
t(_)::something(interest,wa). % TODO
t(_)::something(interest,wheat). % TODO
t(_)::something(interest,year). % TODO
