% YOUR MODEL
t(_)::something(interest,092). % TODO
t(_)::something(interest,1987). % TODO
t(_)::something(interest,agricultur). % TODO
t(_)::something(interest,bank). % TODO
t(_)::something(interest,corn). % TODO
t(_)::something(interest,crop). % TODO
t(_)::something(interest,cut). % TODO
t(_)::something(interest,depart). % TODO
t(_)::something(interest,dlr). % TODO
t(_)::something(interest,expect). % TODO
t(_)::something(interest,export). % TODO
t(_)::something(interest,farm). % TODO
t(_)::something(interest,farmer). % TODO
t(_)::something(interest,govern). % TODO
t(_)::something(interest,grain). % TODO
t(_)::something(interest,ha). % TODO
t(_)::something(interest,import). % TODO
t(_)::something(interest,market). % TODO
t(_)::something(interest,mln). % TODO
t(_)::something(interest,offer). % TODO
t(_)::something(interest,offici). % TODO
t(_)::something(interest,payment). % TODO
t(_)::something(interest,pct). % TODO
t(_)::something(interest,plant). % TODO
t(_)::something(interest,price). % TODO
t(_)::something(interest,program). % TODO
t(_)::something(interest,rate). % TODO
t(_)::something(interest,reuter). % TODO
t(_)::something(interest,said). % TODO
t(_)::something(interest,sourc). % TODO
t(_)::something(interest,soviet). % TODO
t(_)::something(interest,thi). % TODO
t(_)::something(interest,today). % TODO
t(_)::something(interest,tonn). % TODO
t(_)::something(interest,trade). % TODO
t(_)::something(interest,wa). % TODO
t(_)::something(interest,week). % TODO
t(_)::something(interest,wheat). % TODO
t(_)::something(interest,winter). % TODO
t(_)::something(interest,year). % TODO
t(_)::something(grain,092). % TODO
t(_)::something(grain,1987). % TODO
t(_)::something(grain,agricultur). % TODO
t(_)::something(grain,bank). % TODO
t(_)::something(grain,corn). % TODO
t(_)::something(grain,crop). % TODO
t(_)::something(grain,cut). % TODO
t(_)::something(grain,depart). % TODO
t(_)::something(grain,dlr). % TODO
t(_)::something(grain,expect). % TODO
t(_)::something(grain,export). % TODO
t(_)::something(grain,farm). % TODO
t(_)::something(grain,farmer). % TODO
t(_)::something(grain,govern). % TODO
t(_)::something(grain,grain). % TODO
t(_)::something(grain,ha). % TODO
t(_)::something(grain,import). % TODO
t(_)::something(grain,market). % TODO
t(_)::something(grain,mln). % TODO
t(_)::something(grain,offer). % TODO
t(_)::something(grain,offici). % TODO
t(_)::something(grain,payment). % TODO
t(_)::something(grain,pct). % TODO
t(_)::something(grain,plant). % TODO
t(_)::something(grain,price). % TODO
t(_)::something(grain,program). % TODO
t(_)::something(grain,rate). % TODO
t(_)::something(grain,reuter). % TODO
t(_)::something(grain,said). % TODO
t(_)::something(grain,sourc). % TODO
t(_)::something(grain,soviet). % TODO
t(_)::something(grain,thi). % TODO
t(_)::something(grain,today). % TODO
t(_)::something(grain,tonn). % TODO
t(_)::something(grain,trade). % TODO
t(_)::something(grain,wa). % TODO
t(_)::something(grain,week). % TODO
t(_)::something(grain,wheat). % TODO
t(_)::something(grain,winter). % TODO
t(_)::something(grain,year). % TODO
